_format_version: "1.1"
services:
- connect_timeout: 60000
  host: google.com
  name: foo
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - name: bar
    paths:
    - /bar
    path_handling: v0
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
# plugins:
# - name: prometheus
#   enabled: true
#   protocols:
#   - grpc
#   - grpcs
#   - http
#   - https
