***REMOVED***
- name: Ensure the kong Namespace exists.
  community.kubernetes.k8s:
    api_version: v1
    kind: Namespace
    name: kong
    state: present

- name: Add kong chart repo
  community.kubernetes.helm_repository:
    name: kong
    repo_url: "https://charts.konghq.com"

- name: Deploy control plane node
  community.kubernetes.helm:
    name: control
    chart_ref: kong/kong
    release_namespace: kong
    update_repo_cache: true
    values:
      ingressController:
        enabled: false
        installCRDs: false
      secretVolumes:
      - kong-cluster-cert
      env:
        database: 'off'
        role: control_plane
        cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
        cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
      image:
        repository: kong
        tag: "2.2"
        pullPolicy: IfNotPresent
      admin:
        enabled: true
        type: NodePort
        http:
          enabled: true
          servicePort: 8001
          containerPort: 8001
      postgresql:
        enabled: true
        postgresqlUsername: kong
        postgresqlDatabase: kong
        service:
          port: 5432
      cluster:
        enabled: true
        tls:
          enabled: true
          servicePort: 8005
          containerPort: 8005
      proxy:
        enabled: false
      nodeSelector:
        kubernetes.io/arch: amd64
      serviceMonitor:
        enabled: true
        namespace: monitoring


- name: Deploy data plane node
  community.kubernetes.helm:
    name: data
    chart_ref: kong/kong
    release_namespace: kong
    update_repo_cache: true
    values:
      ingressController:
        enabled: false
        installCRDs: false
      secretVolumes:
      - kong-cluster-cert
      env:
        database: "off"
        role: data_plane
        cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
        cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
        lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
        cluster_control_plane: control-kong-cluster.kong.svc.cluster.local:8005
      image:
        repository: kong
        tag: "2.2"
        pullPolicy: IfNotPresent
      admin:
        enabled: false
      postgresql:
        enabled: true
        postgresqlUsername: kong
        postgresqlDatabase: kong
        service:
          port: 5432
      manager:
        enabled: false
      proxy:
        enabled: false
      nodeSelector:
        kubernetes.io/arch: amd64
      serviceMonitor:
        enabled: true
        namespace: monitoring